dist: xenial
sudo: required

language: php

env:
  - TEST_SITE_DIR=docker

matrix:
  fast_finish: true
  allow_failures:
    - php: 7.3

services:
  - docker

before_install:
  # Pre-validate the composer.json file.
  - composer validate
  # Speed up the build.
  - composer global require hirak/prestissimo
  - phpenv config-rm xdebug.ini || echo "xdebug not available"
  # Add phpcs.xml.
  - cp phpcs.dist.xml phpcs.xml
  # Make sure there are no script permission issues.
  - sudo chmod +x .travis-ci -R

stages:
  # Stage for static checks, e.g PHP lint, PHPCS.
  - static_checks
  # Stage for dynamic checks, e.g PHPUnit.
  - dynamic_checks

jobs:
  include:
    - stage: static_checks
      php:
        - 5.6
        - 7.0
        - 7.1
        - 7.2
        - 7.3
      before_install:
        - .travis-ci/install-global-packages.sh
      script:
        - parallel-lint
        - phpcs --standard=phpcs.xml .

    # @todo: Currently only runs on php7.2 as the used docker image is 7.2 as well.
    # @todo: Update, so docker image tags can be set dynamically.
    - stage: dynamic_checks
      php:
        - 7.2
      before_install:
        - .travis-ci/create-project.sh
        - .travis-ci/install-docker-site.sh
      script:
        - .travis-ci/start-dynamic-tests.sh

notifications:
  email:
    on_failure: change
    on_success: change
