dist: xenial
sudo: required

language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3

env:
  global:
    - COMPOSER_BIN_DIR=/home/travis/.config/composer/bin

matrix:
  fast_finish: true
  allow_failures:
    - php: 7.3

services:
  - docker

before_install:
  # Pre-validate the composer.json file.
  - composer validate
  # Speed up the build.
  - composer global require hirak/prestissimo
  - phpenv config-rm xdebug.ini || echo "xdebug not available"
  # Add phpcs.xml.
  - cp phpcs.dist.xml phpcs.xml
  # Make sure there are no script permission issues.
  - sudo chmod +x .travis-ci -R
  - .travis-ci/install-global-packages.sh

# These run in the default "Test" stage.
script:
  - echo "Running against $(php -v).."
  - ${COMPOSER_BIN_DIR}/parallel-lint .
  - ${COMPOSER_BIN_DIR}/phpcs --standard=phpcs.xml .

jobs:
  include:
    # @todo: Currently only runs on php7.2 as the used docker image is 7.2 as well.
    # @todo: Update, so docker image tags can be set dynamically.
    # Job/Stage for dynamic checks, e.g PHPUnit.
    - stage: dynamic_checks
      env:
        - TEST_SITE_DIR=docker
      php:
        - 7.2
      install:
        - .travis-ci/create-project.sh
        - .travis-ci/install-docker-site.sh
      script:
        - .travis-ci/start-dynamic-tests.sh

notifications:
  email:
    on_failure: change
    on_success: change
