field.widget.settings.entity_reference_paragraphs_preview:
  type: mapping
  mapping:
    title:
      type: string
    title_plural:
      type: string
    edit_mode:
      type: string
    add_mode:
      type: string
    form_display_mode:
      type: string
    default_paragraph_type:
      type: string
    add_text_needed:
      type: string

field.formatter.settings.parade_entity_reference_revisions_entity_view:
  type: mapping
  mapping:
    view_mode:
      type: string
    link:
      type: boolean

field.widget.settings.link_with_selected_attribute:
  type: mapping
  mapping:
    placeholder_url:
      type: string
    placeholder_title:
      type: label

field.widget.settings.link_cta:
  type: mapping
  mapping:
    placeholder_url:
      type: string
    placeholder_title:
      type: label
    open_on_new_tab:
      type: boolean

field.formatter.settings.link_call_to_action:
  type: field.formatter.settings.link
  label: 'Call to action link format settings'

field.formatter.settings.leaflet_formatter_default:
  type: mapping
  mapping:
    leaflet_map:
      type: string
    height:
      type: string
    zoom:
      type: string
    minPossibleZoom:
      type: integer
    maxPossibleZoom:
      type: integer
    minZoom:
      type: string
    maxZoom:
      type: string
    popup:
      type: string
    icon:
      type: mapping
      mapping:
        icon_url:
          type: string
        shadow_url:
          type: string
        icon_size:
          type: mapping
          mapping:
            x:
              type: string
            y:
              type: string
        icon_anchor:
          type: mapping
          mapping:
            x:
              type: string
            y:
              type: string
        shadow_anchor:
          type: mapping
          mapping:
            x:
              type: string
            y:
              type: string
        popup_anchor:
          type: mapping
          mapping:
            x:
              type: string
            y:
              type: string

field.value.view_mode_selector:
  type: mapping
  mapping:
    value:
      type: string

field.field_settings.view_mode_selector:
  type: mapping
  mapping:
    view_modes:
      type: sequence
      sequence:
        - type: mapping
          mapping:
            enable:
              type: integer
            hide_title:
              type: integer
            icon:
              type: field_default_image
