field.widget.settings.entity_reference_paragraphs_preview:
  type: mapping
  mapping:
    title:
      type: string
    title_plural:
      type: string
    edit_mode:
      type: string
    add_mode:
      type: string
    form_display_mode:
      type: string
    default_paragraph_type:
      type: string

field.formatter.settings.parade_entity_reference_revisions_entity_view:
  type: mapping
  mapping:
    view_mode:
      type: string
    link:
      type: boolean

field.widget.settings.link_with_selected_attribute:
  type: mapping
  mapping:
    placeholder_url:
      type: string
    placeholder_title:
      type: label

field.widget.settings.link_cta:
  type: mapping
  mapping:
    placeholder_url:
      type: string
    placeholder_title:
      type: label
