parade_conditional_field.parade_conditional_field.*:
  type: config_entity
  label: 'Parade conditional field'
  mapping:
    id:
      type: string
      label: 'ID'
    bundle:
      type: string
      label: 'Bundle'
    layouts:
      mapping:
        type: string
        label: 'Layouts'
    view_mode:
      type: string
      label: 'View mode'
    classes:
      mapping:
        type: string
        label: 'Classes'
