field.formatter.settings.leaflet_formatter_aggregated:
  type: mapping
  mapping:
    data_source:
      type: string
    name_field:
      type: string
    description_field:
      type: string
    map:
      type: string
    height:
      type: string
    icon:
      type: mapping
      mapping:
        iconUrl:
          type: string
        shadowUrl:
          type: string
        iconSize:
          x:
            type: string
          y:
            type: string
        iconAnchor:
          x:
            type: string
          y:
            type: string
        shadowAnchor:
          x:
            type: string
          y:
            type: string
        popupAnchor:
          x:
            type: string
          y:
            type: string
    source_field:
      type: string
    auto_zoom:
      type: boolean
