field.formatter.settings.leaflet_formatter_aggregated:
  type: mapping
  mapping:
    leaflet_map:
      type: string
    height:
      type: string
    zoom:
      type: string
    minPossibleZoom:
      type: integer
    maxPossibleZoom:
      type: integer
    minZoom:
      type: string
    maxZoom:
      type: string
    popup:
      type: string
    data_source:
      type: string
    name_field:
      type: string
    description_field:
      type: string
    map:
      type: string
    icon:
      type: mapping
      mapping:
        icon_url:
          type: string
        shadow_url:
          type: string
        icon_size:
          type: mapping
          mapping:
            x:
              type: string
            y:
              type: string
        icon_anchor:
          type: mapping
          mapping:
            x:
              type: string
            y:
              type: string
        shadow_anchor:
          type: mapping
          mapping:
            x:
              type: string
            y:
              type: string
        popup_anchor:
          type: mapping
          mapping:
            x:
              type: string
            y:
              type: string
    source_field:
      type: string
    auto_zoom:
      type: boolean
