parade_demo.settings:
  type: config_object
  label: 'Parade demo settings'
  mapping:
    bundles:
      type: sequence
      label: 'Allowed bundles'
      sequence:
        type: mapping
        label: 'Allowed value with label'
        mapping:
          css_disabled:
            type: string
            label: 'Disabled parade demo css'
